language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_deploy:
  - zip -r SHIM-s-Anatomy *
  - mkdir -p deploy
  - mv SHIM-s-Anatomy.zip deploy/SHIM-s-Anatomy.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: suhyun-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: suhyun-springboot-build #S3 버킷
    key: SHIM-s-Anatomy.zip
    bundle_type: zip
    application: suhyun-spring #웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: suhyun-spring-group #웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait_until_deployed: true

#CI 실행 완료시 메일로 열람
notifications:
  email:
    recipients:
      - lisa9963suhyun@gmail.com